<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Lifelog</title>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" 
		    	rel="stylesheet" 
				integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" 
				crossorigin="anonymous">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
        
    </head>
    <body>
    <?php $session = \Phalcon\Di::getDefault()->get('session');
        
        $auth = $this->session->get('auth');?> 
        <?php if ($auth['role'] != 'Registered User' && $auth['role'] != 'Admin'):?>
        <nav class="navbar navbar-inverse">
        <a href="/lifelog" class="navbar-brand">Lifelog</a>
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url->getBaseUri()?>/blog/index">Search Blog</a></li>
                <li><a href="<?php echo $this->url->getBaseUri()?>/user/login">login</a></li>
                <li><a href="<?php echo $this->url->getBaseUri()?>/user/new">Register</a></li>
            </ul>
        </nav> 
        <?php endif; ?>
        <?php if ($auth['role'] == 'Registered User' && $auth['role'] != 'Admin' && $auth['role'] != 'Guest'):?>
        <nav class="navbar navbar-inverse">
        <a href="/lifelog" class="navbar-brand">Lifelog</a>
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url->getBaseUri()?>/blog/index">Search Blog</a></li>
                <li><a href="<?php echo $this->url->getBaseUri()?>/blog/new">Create Blog</a></li>
                <li><a href="<?php echo $this->url->getBaseUri()?>/user/logout">Logout</a></li>
            </ul>
        </nav>
        <?php endif; ?>
        <?php if ($auth['role'] == 'Admin' && $auth['role'] != 'Registered User' && $auth['role'] != 'Guest'):?>
        <nav class="navbar navbar-inverse">
        <a href="/lifelog" class="navbar-brand">Lifelog</a>
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url->getBaseUri()?>/blog/index">Search Blog</a></li>
                <li><a href="<?php echo $this->url->getBaseUri()?>/blog/new">Create Blog</a></li>
                <li><a href="<?php echo $this->url->getBaseUri()?>/user/logout">Logout</a></li>
            </ul>
        </nav>
        <?php endif; ?>
        
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>
