<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["blog", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit blog
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "blog/save",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data"
        ]
    );
?> 

<!--input form-->
<div class="form-group">
    <label for="fieldTitle" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBlogContent" class="col-sm-2 control-label">Edit Content</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["blog_content", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldBlogContent"]) ?>
    </div>
</div>


<div class="form-group">
    <label for="fieldImageFile" class="col-sm-2 control-label">Upload new image </label>
    <div class="col-sm-10">
        <?php echo $this->tag->fileField(["imageFile", "size" => 30, "class" => "form-control", "id" => "fieldImageFile"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>
<?php echo $this->tag->hiddenField("blog_id") ?>
<?php echo $this->tag->endForm(); ?>
