<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search tagblog
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["tagblog/new", "Create tagblog"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "tagblog/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldTag" class="col-sm-2 control-label">Tag</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tag", "type" => "number", "class" => "form-control", "id" => "fieldTag"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBlog" class="col-sm-2 control-label">Blog</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["blog", "type" => "number", "class" => "form-control", "id" => "fieldBlog"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
